
name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.*'
      - run: dotnet publish -c Release --runtime win-x64
      - run: powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\WotBanListFull\bin\Release\net7.0\win-x64\publish -DestinationPath .\WotBanListFull.zip
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "WotBanListFull.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        
